Documentation for binding powers and signs
nengo/nengo-spa pull request #282
Opened 2021-04-18 09:51 UTC by jgosmann

**Motivation and context:**
This adds the user guide documentation for binding powers and signs (PR #271).

**Interactions with other PRs:**
Based on #271 implementing the actual feature

**How has this been tested?**
Built documentation and looked it.

**How long should this take to review?**

- Average (neither quick nor lengthy)

**Types of changes:**

- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [ ] I have included a changelog entry.
- [n/a] I have added tests to cover my changes.
- [n/a] I have run the test suite locally and all tests passed.

**Still to do:**

* [ ] TODOs, documentation for `SemanticPointer` binding powers once implemented.
* [ ] proof read

2021-04-21 15:48 UTC, arvoelke commented
One thing I wanted to make sure to post here so that it's not forgotten is this comment https://github.com/nengo/nengo-spa/pull/271#discussion_r595714549 which was the realization that the default implementation for `abs` in the algebra is:
```
return self.bind(self.sign(v).to_vector(len(v)), v)
```
which corresponds perfectly with this definition of sign:
```
sign(z) = z / abs(z)
```
which is the same definition used for integers and complex numbers. That is, if you cross-multiply you get:
```
abs(z) = (1 / sign(z)) * z
```
and then `to_vector` is what is generating `1 / sign(z)`.

2021-08-04 21:13 UTC, bjkomer requested changes
LGTM. Just noticed a few typos

2021-08-04 21:13 UTC, bjkomer commented on docs/pyplots/power_similarity.py
> +
missing numpy import

2021-11-06 17:43 UTC, jgosmann commented
Finally gave this another proof read myself. If this also looks good to you, @bjkomer, @arvoelke, please approve the PR and we can hopefully get the binding powers shipped soon 🚀 .

2021-11-08 18:30 UTC, arvoelke approved these changes

2021-11-09 21:09 UTC, merged